name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  infrastructure:
    runs-on: ubuntu-latest

    steps:
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: actions/checkout@v3
        with:
          path: rust

      - uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: rg-chenette-prod-001
          template: main.bicep
